sudo: required

services:
  - docker

language: bash

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t tiagodeoliveira/docker-shell:latest .
  - docker build -t tiagodeoliveira/docker-shell:alpine -f Dockerfile.alpine .

deploy:
  provider: script
  script: 
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker push tiagodeoliveira/docker-shell:latest
    docker push tiagodeoliveira/docker-shell:alpine
  on:
    branch: master

